#!/bin/bash
#	 Upanix - An x86 based Operating System
#	 Copyright (C) 2011 'Prajwala Prabhakar' 'srinivasa_prajwal@yahoo.co.in'
#																			 
#	 This program is free software: you can redistribute it and/or modify
#	 it under the terms of the GNU General Public License as published by
#	 the Free Software Foundation, either version 3 of the License, or
#	 (at your option) any later version.
#																			 
#	 This program is distributed in the hope that it will be useful,
#	 but WITHOUT ANY WARRANTY; without even the implied warranty of
#	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	 GNU General Public License for more details.
#																			 
#	 You should have received a copy of the GNU General Public License
#	 along with this program.  If not, see <http://www.gnu.org/licenses/

#Customized Qemu Run Script -- Self Written
clear

OVMF_VERSION=$1

SUDO_PW=""
if [ -f .sudopw ]
then
  SUDO_PW=`cat .sudopw`
else
  echo "Don't find .sudopw file. Create a (secure) file .sudopw containing sudo password"
  exit 1
fi

if [ "$BOOT_USB_DEVICE_NAME" = "" -a "$BOOT_USB_DEVICE_ID" != "" ]
then
  devicename=`udevadm info --query=all -n disk/by-id/$BOOT_USB_DEVICE_ID | grep "^N:" | cut -d":" -f2 | tr -d " "`
  if [ $? -eq 0 ]
  then
    BOOT_USB_DEVICE_NAME=$devicename
  fi
fi

if [ "$BOOT_USB_DEVICE_NAME" = "" ]
then
  BOOT_DRIVE="$UPANIX_HOME/USBImage/300MUSB.img"
else
  BOOT_DRIVE="/dev/$BOOT_USB_DEVICE_NAME"
fi

echo -e "\n\n*****************************************************************************\n\n"
echo -e "					Booting from $OVMF_VERSION, `basename $BOOT_DRIVE`"
echo -e "\n\n*****************************************************************************\n\n"

sleep 1

#-hda $UPANIX_HOME/USBImage/30MUSB.img
#-usbdevice disk:$UPANIX_HOME/USBImage/30MUSB.img
#-hda /dev/sda \
#
#-drive if=none,id=usbdrive,file=/dev/sdb \
#-drive if=none,id=usbdrive,file=$UPANIX_HOME/USBImage/300MUSB.img \

QEMU_PATH=
#echo $SUDO_PW | sudo -S qemu-system-x86_64 \
qemu-system-x86_64 \
-serial file:serial_debug.log \
-L $UPANIX_HOME/ovmf.$OVMF_VERSION \
-bios OVMF.fd \
-m 256 \
-smp 1 \
-net none \
-usb \
-drive if=none,id=usbbootdrive,file=$BOOT_DRIVE \
-drive if=none,id=usbdrive1,file=$UPANIX_HOME/USBImage/300MUSB.img \
-drive if=none,id=usbdrivex,file=$UPANIX_HOME/USBImage/300MUSB_xhci.img \
-device usb-ehci,id=ehci \
-device usb-storage,bus=ehci.0,drive=usbbootdrive \
-device nec-usb-xhci,id=xhci \
-device usb-storage,bus=xhci.0,port=1,drive=usbdrivex \
-device usb-hub,bus=xhci.0,port=3
