#!/bin/bash
#	 Upanix - An x86 based Operating System
#	 Copyright (C) 2011 'Prajwala Prabhakar' 'srinivasa_prajwal@yahoo.co.in'
#																			 
#	 This program is free software: you can redistribute it and/or modify
#	 it under the terms of the GNU General Public License as published by
#	 the Free Software Foundation, either version 3 of the License, or
#	 (at your option) any later version.
#																			 
#	 This program is distributed in the hope that it will be useful,
#	 but WITHOUT ANY WARRANTY; without even the implied warranty of
#	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	 GNU General Public License for more details.
#																			 
#	 You should have received a copy of the GNU General Public License
#	 along with this program.  If not, see <http://www.gnu.org/licenses/

#Customized Qemu Run Script -- Self Written
clear

BootFileType=$1

if [ "$#" -eq "0" -o "$1" = "image" ]
then

	BootFileType="image"
	FDA=$UPANIX_HOME/floppy/1.44M-FLOPPY.img
	FDB=$UPANIX_HOME/floppy/DRV1.FDD.img
	
elif [ "$1" = "BT" ]
then

	FDA=$UPANIX_HOME/floppy/BootTest.img
	FDB=$UPANIX_HOME/floppy/DRV1.FDD.img


elif [ "$1" = "floppy" ]
then

	FDA=/dev/fd0
	FDB=$UPANIX_HOME/floppy/DRV1.FDD.img

elif [ "$1" = "grub_ext" ]
then

	FDA=$UPANIX_HOME/floppy/GrubFloppy_ext.img
	FDB=$UPANIX_HOME/floppy/DRV1.FDD.img

elif [ "$1" = "grub_mos" ]
then

	FDA=$UPANIX_HOME/floppy/GrubFloppy_mos.img
	FDB=$UPANIX_HOME/floppy/DRV1.FDD.img

elif [ "$1" = "setup_ext" ]
then

	FDA=$UPANIX_HOME/floppy/RawGrubFloppy.img
	FDB=$UPANIX_HOME/floppy/GrubFloppy_ext.img

elif [ "$1" = "install_mos" ]
then

	FDA=$UPANIX_HOME/floppy/RawGrubFloppy.img
	FDB=$UPANIX_HOME/floppy/GrubFloppy_mos.img

elif [ "$1" = "setup_mos" ]
then

	FDA=$UPANIX_HOME/floppy/GrubFloppy_ext.img
	FDB=$UPANIX_HOME/floppy/GrubFloppy_mos.img

fi

SUDO=""
if [ "$2" = "sudo" ]
then
	SUDO=sudo
fi

echo -e "\n\n*****************************************************************************\n\n"
echo -e "					Booting From $BootFileType File"
echo -e "\n\n*****************************************************************************\n\n"

sleep 1

#-hda $UPANIX_HOME/USBImage/30MUSB.img
#-usbdevice disk:$UPANIX_HOME/USBImage/30MUSB.img
#-hda /dev/sda \


QEMU_PATH=
$SUDO qemu-system-x86_64 \
-serial file:serial_debug.log \
-fda $FDA \
-fdb $FDB \
-boot a \
-m 128 \
-smp 1 \
-net none \
\
-drive if=none,id=usbdrive,file=$UPANIX_HOME/USBImage/300MUSB.img \
\
-usb \
-device usb-ehci,id=ehci \
-device usb-storage,bus=ehci.0,drive=usbdrive \
\
-hda $UPANIX_HOME/HDImage/30MHD.img
